spring:
    application:
        name: User-Car-Demo
    datasource:
        url: jdbc:mysql://localhost:3306/User-Car-System?createDatabaseIfNotExist=true
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
    #    password: <your password>
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        format-sql: true